# This patch enables TLS configuration for the ServiceMonitor to scrape metrics
# from the manager pod when cert-manager certificates are used.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubevirt-wol-controller-manager-metrics-monitor
spec:
  endpoints:
  - path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      ca:
        secret:
          name: metrics-server-cert
          key: ca.crt
      serverName: metrics-service.kubevirt-wol-system.svc

