apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-wol-agent
  labels:
    app.kubernetes.io/name: kubevirt-wol
    app.kubernetes.io/component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-wol-scc-user
subjects:
- kind: ServiceAccount
  name: wol-agent
  namespace: system

