apiVersion: v1
kind: ServiceAccount
metadata:
  name: wol-agent
  namespace: system
  labels:
    app.kubernetes.io/name: wol-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: kubevirt-wol

