# permissions for end users to view configs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-wol
    app.kubernetes.io/managed-by: kustomize
  name: config-viewer-role
rules:
- apiGroups:
  - wol.pillon.org
  resources:
  - configs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wol.pillon.org
  resources:
  - configs/status
  verbs:
  - get
