---
apiVersion: v1
kind: Service
metadata:
  name: grpc  # Will become kubevirt-wol-grpc with namePrefix from kustomization.yaml
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kubevirt-wol
    app.kubernetes.io/component: grpc
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP
