apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-wol-wol-scc-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-wol-scc-user
subjects:
  - kind: ServiceAccount
    name: kubevirt-wol-controller-manager
    namespace: kubevirt-wol-system
  - kind: ServiceAccount
    name: kubevirt-wol-wol-agent
    namespace: kubevirt-wol-system

