apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: kubevirt-wol.v0.0.1
spec:
  install:
    spec:
      clusterPermissions:
        - serviceAccountName: kubevirt-wol-wol-agent
          rules:
            - apiGroups:
                - security.openshift.io
              resources:
                - securitycontextconstraints
              resourceNames:
                - kubevirt-wol-wol-scc
              verbs:
                - use